-- database/postgres/02_week4_aggregates_setops.sql
-- Satisfies Rubric: Aggregate Functions, GROUP BY, HAVING, Set Operations

-- 1. Total complaints versus total severe complaints
SELECT 
    COUNT(*) AS total_complaints,
    SUM(CASE WHEN reported_score < 40 THEN 1 ELSE 0 END) AS total_severe_complaints
FROM condition_reports;

-- 2. Average condition score, Highest, and Lowest score by Location
SELECT 
    loc.region_name,
    COUNT(r.road_id) AS total_roads,
    ROUND(AVG(rc.condition_score), 2) AS avg_score,
    MAX(rc.condition_score) AS best_score,
    MIN(rc.condition_score) AS worst_score
FROM locations loc
JOIN roads r ON loc.location_id = r.location_id
JOIN road_conditions rc ON r.road_id = rc.road_id
GROUP BY loc.region_name
HAVING COUNT(r.road_id) > 0
ORDER BY avg_score ASC;

-- 3. Complaint count per road (Only showing roads with > 2 complaints)
SELECT 
    r.name AS road_name,
    COUNT(cr.report_id) AS complaint_count
FROM roads r
JOIN condition_reports cr ON r.road_id = cr.road_id
GROUP BY r.name
HAVING COUNT(cr.report_id) > 2
ORDER BY complaint_count DESC;

-- 4. Count of complaints submitted by users vs generated by AI
SELECT 
    CASE 
        WHEN user_id IS NOT NULL THEN 'User Submitted'
        WHEN model_id IS NOT NULL THEN 'AI Generated'
    END AS report_source,
    COUNT(*) AS source_count
FROM condition_reports
GROUP BY 
    CASE 
        WHEN user_id IS NOT NULL THEN 'User Submitted'
        WHEN model_id IS NOT NULL THEN 'AI Generated'
    END;

-- 5. Set Operations: UNION
-- Roads reported by users UNION roads flagged severe by AI
SELECT r.road_id, r.name, 'Reported by User' AS alert_reason
FROM roads r
JOIN condition_reports cr ON r.road_id = cr.road_id
WHERE cr.user_id IS NOT NULL
UNION
SELECT r.road_id, r.name, 'AI Flagged Severe' AS alert_reason
FROM roads r
JOIN condition_reports cr ON r.road_id = cr.road_id
WHERE cr.model_id IS NOT NULL AND cr.reported_score < 40;

-- 6. Set Operations: INTERSECT
-- Roads in 'SEVERE' category INTERSECT roads with more than 3 unresolved complaints
SELECT r.road_id, r.name
FROM roads r
JOIN road_conditions rc ON r.road_id = rc.road_id
JOIN condition_categories cc ON rc.category_id = cc.category_id
WHERE cc.category_name = 'SEVERE'
INTERSECT
SELECT r.road_id, r.name
FROM roads r
JOIN condition_reports cr ON r.road_id = cr.road_id
WHERE cr.status = 'PENDING'
GROUP BY r.road_id, r.name
HAVING COUNT(cr.report_id) > 3;

-- 7. Set Operations: EXCEPT
-- Roads with active complaints EXCEPT roads already being resolved or acted upon
SELECT r.road_id, r.name
FROM roads r
JOIN condition_reports cr ON r.road_id = cr.road_id
WHERE cr.status = 'PENDING'
EXCEPT
SELECT r.road_id, r.name
FROM roads r
JOIN condition_reports cr ON r.road_id = cr.road_id
JOIN admin_actions aa ON cr.report_id = aa.report_id;
