spring.application.name=monitor
server.port=${PORT:8080}

# --- PRIMARY CONFIG: POSTGRES (Local Docker) ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/georoad}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=your_super_secret_key_which_is_long_enough_for_sha256_algorithm
jwt.expiration=86400000

# AIService URL
ai.service.url=http://localhost:8000/predict

# Supabase S3 Configuration
supabase.s3.endpoint=https://bthspkxlifbnwfichcke.storage.supabase.co/storage/v1/s3
supabase.s3.region=eu-central-1
supabase.s3.access-key=ca5e80dcf585a591f4150d92b3b99e1c
supabase.s3.secret-key=41194319c395e3f9bd879b91284018a2ee9c120e8fe3b688a8613742c36feb23
supabase.s3.bucket=complaints
