spring.datasource.url=jdbc:h2:mem:georoad;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# JWT & AI (Shared)
jwt.secret=your_super_secret_key_which_is_long_enough_for_sha256_algorithm
jwt.expiration=86400000
ai.service.url=http://localhost:8000/predict
